CREATE TABLE TBL_PIZZA_01 (
    PCODE CHAR(4) NOT NULL,
    PNAME VARCHAR2(30),
    COST NUMBER(7),
    CONSTRAINT PK_PIZZA PRIMARY KEY (PCODE)
);

CREATE TABLE TBL_SHOP_01 (
    SCODE CHAR(4) NOT NULL,
    SNAME VARCHAR2(20),
    CONSTRAINT PK_SHOP PRIMARY KEY (SCODE)
);

CREATE TABLE TBL_SALELIST_01 (
    SALENO NUMBER(7) NOT NULL,
    SCODE CHAR(4) NOT NULL,
    SALEDATE DATE,
    PCODE CHAR(4) NOT NULL,
    AMOUNT NUMBER(5),
    CONSTRAINT PK_SALELIST PRIMARY KEY (SALENO)
);